### ISSUE TITLE
CLOUD daily ODP-dataset is missing

### ISSUE THREAD

**Issue by HerzogStephan** [CCI-Tools/cate-core#338]
### Expected behavior

Daily CLOUD-dataset "esacci.CLOUD.day.L3U.CLD_PRODUCTS.multi-sensor.Envisat.MERISAATSR_ENVISAT.1-0.r1" being available.

### Actual behavior

It is not available

### Steps to reproduce the problem

1. cate ds list

### Specifications 

Linux, cate-0.9.0_dev5

**Comment by mzuehlke** [comment]
The ODP seems to have only the CLOUD datasets from phase 2. Earlier datasets seem to be no longer online.

**Comment by kbernat** [comment]
ESGF:
1. | esacci.CLOUD.day.L3U.CLD_PRODUCTS.multi-sensor.Envisat.MERISAATSR_ENVISAT.1-0.r1 Data Node: esgf-data1.ceda.ac.uk Version: 20170119 Total Number of Files (for all variables): 1096[ Show Metadata ]   [ Show Files ]   [ THREDDS Catalog ]   [ WGET Script ]   [ Tech Note ]
-- | --

There is no Phase 2 available on ESGF. And the problem is that CSW service does not contain proper links to data download for both Phases.

Problem will be reported to CCI ODP data administrator.

**Comment by forman** [comment]
@kbernat why do you think this is a blocker. It first it is an ODP issue and its resolution is outside Cate. Second, we have other issues that are way "more blocking" from Cate perspective, e.g. in particular #287.

**Comment by kbernat** [comment]
With the new release of Clouds products CCI Cloud team changed the granularity, so the various AVHRR instruments are now either grouped under AVHRR-AM or AVHRR-PM.
